# G-CLEF Wavefinder Configuration File
# This file is written in TOML: https://toml.io/en/
# See Explanation of Options at the bottom of the file.

[app]
update_rate = 0.016667

[camera]
run_mode    = "NORMAL"
bits        = 8
freq_mode   = 6
resolution  = {rows = 1280, columns = 960}
bin_mode    = "NO_BIN"
nBuffer     = 24
exposure    = 50.0
fps         = 10.0
gain        = 15

[motion.zaber]
ports = ["COM3", "COM6"]

[motion.zaber.axis_names]
"focal_x"   =  33938
"focal_y"   =  33937
"focal_z"   =  33939
"cfm2_x"    = 110098
"cfm2_y"    = 113059

[motion.galil]
address         = "192.168.1.19"
acceleration    = 2000000
deceleration    = 2000000
move_speed      =  100000
home_speed      =    5000
encdr_cnts_deg  =     800
drive_cnts_deg  =   10000

[motion.galil.axis_names]
"cfm1_az"   = "A"
"cfm1_el"   = "B"
"cfm2_az"   = "C"
"cfm2_el"   = "D"

[motion.limits]
"focal_z"   = {min =   0.0, max = 15.0}
"cfm1_az"   = {min = -10.0, max = 10.0}
"cfm1_el"   = {min = -10.0, max = 10.0}
"cfm2_az"   = {min = -10.0, max = 10.0}
"cfm2_el"   = {min = -10.0, max = 10.0}

[positioner]
x_axis      = "focal_x"
y_axis      = "focal_y"

[focuser]
focus_axis          = "focal_z"
points_per_pass     = 10
frames_per_point    =  3
minimum_move        =  0.001

# Explanation of Options
# Any settings not set will use defaults, shown in [brackets]
# 
# [app]
# update rate in seconds; default = 1/60
#
# [camera]
# run_mode:     ["NORMAL"] (streaming video) or "TRIGGER" (single exposure)
# bits:         camera bitrate [8] or 12
# freq_mode:    freq = full_speed / (2^freq_mode), is one of [0], 1, 2, 3, 4
# resolution:   camera resolution: [1280, 960]
# bin_mode:     camera bin mode is one of
#                   ["NO_BIN"], "BIN1X2", "BIN1X3", "BIN1X4", "SKIP"
# nBuffer:      size of camera buffer, maximum of [24]
# exposure:     exposure time in milliseconds, in increments of 0.05ms,
#                   default [50.0]
# fps:          "NORMAL" mode target frames per second, default [10.0]
# gain:         6 to 41 dB, inclusive, [15] dB recommended for "NO_BIN" mode,
#                   lower to 6-8 for binning modes
#
# [motion.zaber]
# ports:        list of serial ports to scan [all]
#
# [motion.zaber.axis_names]
# list all zaber axes as "name" = serial_number, e.g.
# "focal_x" = 33938
#
# [motion.galil]
# address:      IP address of Newmark controller ["192.168.1.19"]
# acceleration: in drive counts [2000000]
# deceleration: in drive counts [2000000]
# move_speed:   in drive counts [100000]
# home_speed:   in drive counts [5000]
# encdr_cnts_deg:   encoder counts per degree [800]
# drive_cnts_deg:   drive counts per degree [10000]
#
# [motion.galil.axis_names]
# list all galil/newmark axes as "name" = "channel letter", e.g.
# "cfm1_az" = "A"
#
# [motion.limits]
# list all motion limits (both zaber & galil) as "name" = {min = XX, max = XX}
# where min and max are the minimum and maximum position in mm or degrees, e.g.
# "focal_z" = {min =   0.0, max = 15.0}
# "cfm1_az" = {min = -10.0, max = 10.0}
#
# [positioner]
# x_axis: name of axis to use as x-axis when positioning camera
# y_axis: name of axis to use as y-axis when positioning camera
#
# [focuser]
# focus_axis:       name of axis to use as z-axis when focusing camera
# points_per_pass:  number of focus points per focusing pass [10]
# frames_per_point: number of frames to measure at each point (averaged) [3]
# minimum_move:     minimum focus movement resolution, in mm [0.001]
