# G-CLEF Wavefinder Minimal Configuration File

[camera]
exposure    = 0.10

[motion.zaber]
ports       = ["COM3", "COM6"]

[motion.galil]
address     = "192.168.1.19"

[motion.limits]
"focal_z"   = {min =   0.0, max = 15.0}
"cfm1_az"   = {min = -10.0, max = 10.0}
"cfm1_el"   = {min = -10.0, max = 10.0}
"cfm2_az"   = {min = -10.0, max = 10.0}
"cfm2_el"   = {min = -10.0, max = 10.0}

[focuser]
points_per_pass     = 10
frames_per_point    =  3
minimum_move        =  0.001
