# G-CLEF Wavefinder Minimal Configuration File

[camera]
exposure    = 0.10

[motion.zaber]
ports       = ["COM3", "COM6"]

[motion.galil]
address     = "192.168.1.19"

[motion.limits]
"detector z"        = {min =   0.0, max = 15.0}
"cfm1 azimuth"      = {min = -30.0, max = 30.0}
"cfm1 elevation"    = {min = -30.0, max = 30.0}
"cfm2 azimuth"      = {min = -30.0, max = 30.0}
"cfm2 elevation"    = {min = -30.0, max = 30.0}

[focuser]
points_per_pass     = 10
frames_per_point    =  3
minimum_move        =  0.001
