[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
include = ["wavefinder"] 

[project]
name = "GCLEF-Wavefinder"
version = "0.0.1"
authors = [
  { name="Cem Onyuksel", email="cem.onyuksel@cfa.harvard.edu" },
  { name="Colby Jergenson", email="colby.jurgenson@cfa.harvard.edu" }
]
description = "Measure optical performance at various wavelengths"
readme = "README.md"
requires-python = ">=3.11"
# dependencies = [
#     "numpy",
#     "tkinter"
# ]
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
]

# [project.urls]
# "Homepage" = "https://github.com/pypa/sampleproject"
# "Bug Tracker" = "https://github.com/pypa/sampleproject/issues"